apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  type: ClusterIP
  selector:
    app: nginx-multitool
  ports:
    - name: nginx-http
      port: 80
      targetPort: nginx-http

    - name: multitool-http
      port: 8080
      targetPort: multitool-http
